# Generated by Django 5.2.4 on 2025-07-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.IntegerField()),
                ('dba_name', models.TextField()),
                ('aka_name', models.TextField()),
                ('license', models.IntegerField()),
                ('facility_type', models.TextField()),
                ('risk', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.CharField(max_length=255)),
                ('inspection_date', models.TextField()),
                ('inspection_type', models.TextField()),
                ('results', models.TextField()),
                ('violations', models.TextField()),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.TextField()),
            ],
        ),
    ]
